config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resource :landing

  resource :profile

  resources :resumes do
    resources :employers
    resources :schools
  end

  get "/resume", to: "resumes#show"

  if ENV["LANDING_PAGE_REDIRECT"].present?
    root to: redirect(ENV["LANDING_PAGE_REDIRECT"], status: 302)
  else
    root "landings#show"
  end
end

app/models/resume.rb
class Resume < ApplicationRecord
  belongs_to :user

  has_many :employers, dependent: :destroy
  has_many :schools, dependent: :destroy

  before_validation :slugify

  def phone
    super.presence || user.phone
  end

  def email
    super.presence || user.email
  end

  def preferred_pronouns
    super.presence || user.preferred_pronouns
  end

  def portfolio_url
    super.presence || user.portfolio_url
  end

  def full_portfolio_url
    return if portfolio_url.blank?

    url = portfolio_url.sub(/\/$/, "") # Remove trailing slash
    if /\Ahttps?:\/\//.match?(url)
      url
    else
      "https://#{url}"
    end
  end

  def display_portfolio_url
    return if portfolio_url.blank?

    full_portfolio_url.gsub(/\Ahttps?:\/\/(www\.)?/, "")
  end

  def name
    alias_name.presence || user&.name
  end

  def to_param
    slug
  end

  private

  def slugify
    self.slug = "#{name} #{field}".parameterize
  end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :require_resume, only: [:show, :edit, :update, :destroy]

  def index
    @resumes = Resume.all.order(created_at: :desc)
  end

  def show
  end

  def new
    authorize Resume, :new?
    @resume = current_user.resumes.new
  end

  def edit
    authorize @resume
  end

  def create
    authorize Resume, :create?
    @resume = current_user.resumes.new(resume_params.merge(user: current_user))
    if @resume.save
      respond_to do |format|
        format.html { redirect_to @resume, notice: I18n.t("resume.created") }
        format.turbo_stream { flash.now[:notice] = I18n.t("resume.created") }
      end
    else
      flash.now[:alert] = I18n.t("resume.not_created")
      render(:new, status: :unprocessable_entity)
    end
  end

  def update
    authorize @resume
    if @resume.update(resume_params)
      respond_to do |format|
        format.html { redirect_to resume_path(id: @resume.slug), notice: I18n.t("resume.updated") }
        format.turbo_stream { flash.now[:notice] = I18n.t("resume.updated") }
      end
    else
      flash.now[:alert] = I18n.t("resume.not_updated")
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @resume
    if @resume.destroy
      respond_to do |format|
        format.html { redirect_to resumes_path, notice: I18n.t("resume.destroyed") }
        format.turbo_stream { flash.now[:notice] = I18n.t("resume.destroyed") }
      end
    else
      flash.now[:alert] = I18n.t("resume.not_destroyed")
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def require_resume
    @resume = Resume.find_by(slug: params[:id]) || current_user&.resumes&.first
    return if @resume

    redirect_to(current_user ? new_resume_path : new_user_session_path)
  end

  def resume_params
    params.require(:resume).permit(
      :field, :summary, :email, :phone, :alias_name, :preferred_pronouns, :portfolio_url
    )
  end
end

app/views/resumes/_add_employer.html.haml
= turbo_frame_tag Employer.new do
  .resume__actions
    = button_to I18n.t('resumes.edit.add_employer'), new_resume_employer_path(resume), method: :get, class: 'button'

app/views/resumes/_add_school.html.haml
= turbo_frame_tag School.new do
  .resume__actions
    = button_to I18n.t('resumes.edit.add_school'), new_resume_school_path(resume), method: :get, class: 'button'

app/views/resumes/_employer.html.haml
= turbo_frame_tag employer do
  .employer
    .employer__info-line
      .employer__info
        = employer.name
      - if employer.location.present?
        .employer__info
          = employer.location
      - if employer.url.present?
        .employer__info
          = link_to(employer.display_url, employer.full_url, target: employer.name)
    - employer.roles.each do |role|
      .role
        .role__info-line
          .role__info
            = role.title
          .role__info
            = role.start_year
            - if role.end_year.present?
              = " – #{role.end_year}"
        .role__accomplishments
          = role.accomplishments
    .employer__actions
      = link_to 'Edit', edit_resume_employer_path(resume_id: employer.resume, id: employer), class: 'button'
      - confirmation_text = I18n.t('employer.confirm_destroy')
      = button_to I18n.t('resource.destroy'), [employer.resume, employer], method: :delete, data: { 'turbo-confirm': confirmation_text }, class: 'button'

app/views/resumes/_form.html.haml
= form_with model: resume || Resume.new, class: 'form' do |form|
  .form__field
    = form.label :field
    = form.text_field :field, placeholder: 'Software Development'
  .form__field
    = form.label :alias_name
    = form.text_field :alias_name, placeholder: resume.user&.name
  .form__field
    = form.label :email
    = form.text_field :email, placeholder: resume.user&.email
  .form__field
    = form.label :phone
    = form.text_field :phone, placeholder: resume.user&.phone
  .form__field
    = form.label :profile
    = form.text_area :profile
  .form__actions
    = form.submit 'Save', class: 'button'

app/views/resumes/_overview_form.html.haml
- classes = bem("form", nil, "resume-overview")
= form_with model: resume || Resume.new, class: classes do |form|
  .form__field
    = form.label :field
    = form.text_field :field, placeholder: 'Software Development'
  .form__field
    = form.label :alias_name
    = form.text_field :alias_name, placeholder: resume.user&.name
  .form__field
    = form.label :email
    = form.text_field :email, value: resume.read_attribute(:email), placeholder: resume.user&.email
  .form__field
    = form.label :phone
    = form.text_field :phone, value: resume.read_attribute(:phone), placeholder: resume.user&.phone
  .form__field
    = form.label :portfolio_url
    = form.text_field :portfolio_url, value: resume.read_attribute(:portfolio_url), placeholder: resume.user&.portfolio_url
  .form__field
    = form.label :preferred_pronouns
    = form.text_field :preferred_pronouns, value: resume.read_attribute(:preferred_pronouns), placeholder: resume.user&.preferred_pronouns
  .form__actions
    = form.submit 'Save', class: 'button'

app/views/resumes/_profile_form.html.haml
- classes = bem("form", nil, "resume-profile")
= form_with model: resume || Resume.new, class: classes do |form|
  .form__field
    = form.label :profile
    = form.text_area :profile
  .form__actions
    = form.submit 'Save', class: 'button'

app/views/resumes/_resume.html.haml
= turbo_frame_tag resume do
  .resume
    .resume__header
      - if resume.preferred_pronouns.present?
        %span{ class: bem("resume", "preferred-pronouns") }
          = resume.preferred_pronouns
      %h2
        = resume.name
      - if resume.field
        %h3.subheader
          = resume.field
    .resume__contact-info
      - if resume.email.present?
        %div{ class: bem("resume", "contact-info-item", "email") }
          = mail_to resume.email
      - if resume.phone.present?
        %div{ class: bem("resume", "contact-info-item", "phone") }
          = resume.phone
      - if resume.portfolio_url.present?
        %div{ class: bem("resume", "contact-info-item", "portfolio_url") }
          = link_to(resume.display_portfolio_url, resume.full_portfolio_url, target: 'portfolio')
    - if resume.summary.present?
      .resume__section
        .resume__section-title
          = I18n.t('resume.summary')
        .resume__section-content
          = resume.summary
    - if resume.employers.present?
      .resume__section
        .resume__section-title
          = I18n.t('resume.work_experience')
        .resume__section-content
          = render resume.employers.sort_by(&:sort_value)
    - if resume.schools.present?
      .resume__section
        .resume__section-title
          = I18n.t('resume.educational_experience')
        .resume__section-content
          = render resume.schools
    .resume__actions
      - unless current_page?(resume_path(id: resume.slug))
        - button_text = I18n.t('resource.show_resource', resource: I18n.t('activerecord.models.resume'))
        = link_to button_text, resume_path(id: resume.slug), class: 'button', data: { turbo: false }
      - if policy(resume).edit?
        - button_text = I18n.t('resource.edit_resource', resource: I18n.t('activerecord.models.resume'))
        = link_to button_text, edit_resume_path(id: resume.slug), class: 'button'
      - if policy(resume).destroy?
        - button_text = I18n.t('resource.destroy_resource', resource: I18n.t('activerecord.models.resume'))
        - confirmation_text = I18n.t('resume.confirm_destroy')
        = button_to button_text, resume, method: :delete, data: { 'turbo-confirm': confirmation_text }, class: 'button'

app/views/resumes/_school.html.haml
= turbo_frame_tag school do
  .school
    .school__info-line
      .school__info
        = school.name
      - if school.location.present?
        .school__info
          = school.location
      - if school.url.present?
        .school__info
          = link_to(school.display_url, school.full_url, target: school.name)
    .school__info-line
      - if school.degree.present? || school.major.present?
        .school__info
          - if school.degree.present?
            = [school.degree.presence, ("(#{school.major})" if school.major.present?)].compact.join(" ")
          - elsif school.major.present?
            = I18n.t('school.coursework', major: school.major)
    - if school.note.present?
      .school__info-line
        .school__info
          = school.note
    .school__actions
      = link_to 'Edit', edit_resume_school_path(resume_id: school.resume, id: school), class: 'button'
      - confirmation_text = I18n.t('school.confirm_destroy')
      = button_to I18n.t('resource.destroy'), [school.resume, school], method: :delete, data: { 'turbo-confirm': confirmation_text }, class: 'button'

app/views/resumes/create.turbo_stream.haml
= turbo_stream.replace "messaging", partial: "layouts/messaging"
= turbo_stream.replace "new_resume", @resume

app/views/resumes/destroy.turbo_stream.haml
= turbo_stream.remove @resume
= turbo_stream.replace "messaging", partial: "layouts/messaging"

app/views/resumes/edit.html.haml
= turbo_frame_tag @resume do
  .resume
    .resume__header
      %h2
        = I18n.t('resumes.edit.header')
    .resume__section
      .resume__section-title
        = I18n.t('resume.overview')
      .resume__section-content
        = render partial: 'overview_form', locals: { resume: @resume }
    .resume__section
      .resume__section-title
        = I18n.t('resume.summary')
      .resume__section-content
        = render partial: 'summary_form', locals: { resume: @resume }
    - if @resume.persisted?
      .resume__section
        .resume__section-title
          = I18n.t('resume.work_experience')
        .resume__section-content
          = turbo_frame_tag "employers" do
            - @resume.employers.sort_by(&:sort_value).each do |employer|
              = render partial: 'resumes/employer', locals: { employer: }
          = render partial: 'resumes/add_employer', locals: { resume: @resume }
      .resume__section
        .resume__section-title
          = I18n.t('resume.educational_experience')
        .resume__section-content
          = turbo_frame_tag "schools" do
            - @resume.schools.each do |school|
              = render partial: 'resumes/school', locals: { school: }
          = render partial: 'resumes/add_school', locals: { resume: @resume }

app/views/resumes/index.html.haml
%h2
  = I18n.t("activerecord.models.resume").pluralize

- if @resumes.empty?
  %p
    = I18n.t("resumes.index.empty")
- else
  = render @resumes

- if current_user
  .resume__actions
    = link_to I18n.t("resumes.index.new"), new_resume_path, :class => "button"

app/views/resumes/show.html.haml
= render @resume

app/views/resumes/update.turbo_stream.haml
= turbo_stream.replace(@resume)
= turbo_stream.replace "messaging", partial: "layouts/messaging"