config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resource :landing

  resource :profile

  resources :resumes do
    resources :employers
    resources :schools
  end

  get "/resume", to: "resumes#show"

  if ENV["LANDING_PAGE_REDIRECT"].present?
    root to: redirect(ENV["LANDING_PAGE_REDIRECT"], status: 302)
  else
    root "landings#show"
  end
end

app/views/layouts/_footer.html.haml
.footer
  .footer__line
    = I18n.t("footer.source_code_label")
    - github_project_url = "https://github.com/roberthead/colleague"
    = link_to(github_project_url, github_project_url, target: "github")

app/views/layouts/_messaging.html.haml
- if flash.present?
  .messaging
    - flash.each do |flash_type, message|
      %div{ class: bem("messaging", "message", flash_type) + " closeable", "data-controller": "closeable" }
        .messaging__message-text
          = message
        .messaging__close-widget{ "data-action": "click->closeable#close" }
          = link_to("javascript:void(0)", class: "messaging__close-widget") do
            x

app/views/layouts/_navbar.html.haml
.navbar
  .navbar__title
    %h1
      %a.navbar__title-link{ href: root_path }
        - if ENV["SITE_NAME"].present?
          = ENV["SITE_NAME"]
        - else
          = I18n.t('site.name', default: 'Colleague')
    - if I18n.exists?('site.tagline')
      %h2.navbar__tagline.subheader
        = I18n.t('site.tagline')
  %ul.navbar__menu
    %li.navbar__menu-item
      = link_to I18n.t('activerecord.models.resume').pluralize, resumes_path
    - if signed_in?
      %li.navbar__menu-item
        = link_to I18n.t("application.profile"), profile_path
      %li.navbar__menu-item
        = button_to I18n.t("application.sign_out"), destroy_user_session_path, method: :delete, class: 'button'
    - elsif User.count.positive?
      %li.navbar__menu-item
        = link_to I18n.t('application.sign_in'), new_user_session_path, class: 'button'
    - else
      = link_to(I18n.t('application.sign_up'), new_user_registration_path, class: "button")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Colleague
    %meta{content: "width=device-width,initial-scale=1", name: "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body{ class: bem('controller', '', controller_name) }
    .spread
      .page
        = render partial: "layouts/navbar"
        = turbo_frame_tag "messaging" do
          = render partial: "layouts/messaging"
        %main
          = yield
        %footer
          = render partial: "layouts/footer"